#!/bin/bash
# Request a resource via collective provisioning system
# Usage: ./resource-request.sh --source <url/magnet> --purpose "<reason>" [--size <estimate>] [--auto-approve]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Parse arguments
SOURCE=""
PURPOSE=""
SIZE_ESTIMATE="unknown"
AUTO_APPROVE=false
REQUESTING_AGENT="code"  # Default, can be overridden

while [[ $# -gt 0 ]]; do
    case $1 in
        --source)
            SOURCE="$2"
            shift 2
            ;;
        --purpose)
            PURPOSE="$2"
            shift 2
            ;;
        --size)
            SIZE_ESTIMATE="$2"
            shift 2
            ;;
        --auto-approve)
            AUTO_APPROVE=true
            shift
            ;;
        --from)
            REQUESTING_AGENT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 --source <url/magnet> --purpose \"<reason>\" [--size <estimate>] [--auto-approve] [--from <agent>]"
            exit 1
            ;;
    esac
done

# Validate required arguments
if [[ -z "$SOURCE" || -z "$PURPOSE" ]]; then
    echo "Error: --source and --purpose are required"
    echo "Usage: $0 --source <url/magnet> --purpose \"<reason>\" [--size <estimate>] [--auto-approve] [--from <agent>]"
    exit 1
fi

# Generate request ID
REQUEST_ID=$(uuidgen | tr '[:upper:]' '[:lower:]')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Determine priority based on size and auto-approve
if [[ "$AUTO_APPROVE" == "true" ]]; then
    PRIORITY="NORMAL"
    APPROVAL_STATUS="auto-approved"
else
    PRIORITY="HIGH"
    APPROVAL_STATUS="requires-human-approval"
fi

# Create message file
MESSAGE_FILE="/tmp/resource-request-$REQUEST_ID.md"
cat > "$MESSAGE_FILE" <<EOF
# Resource Request

**Request ID**: $REQUEST_ID
**Requested by**: $REQUESTING_AGENT
**Timestamp**: $TIMESTAMP

## Source
\`\`\`
$SOURCE
\`\`\`

## Purpose
$PURPOSE

## Metadata
- **Estimated Size**: $SIZE_ESTIMATE
- **Approval Status**: $APPROVAL_STATUS
- **Priority**: $PRIORITY

## Actions Required

### For Code Agent
- [ ] Evaluate source safety and legitimacy
- [ ] Check available disk space
- [ ] Verify not already downloaded
- [ ] Proceed with download if $APPROVAL_STATUS = auto-approved
- [ ] Request human approval if needed

### For Human (if approval required)
- [ ] Review source and purpose
- [ ] Approve or deny via response message
- [ ] Consider: Is this source trustworthy? Do we have space? Is it needed?

## Response Format
Reply to this message with:
\`\`\`yaml
decision: approved | denied
reason: <optional explanation>
\`\`\`

---
*Generated by collective resource provisioning system*
EOF

# Send via bridge
if [[ "$REQUESTING_AGENT" == "code" ]]; then
    # Code agent sending to human for approval
    "$SCRIPT_DIR/bridge-send.sh" code human "$PRIORITY" "Resource Request: $PURPOSE" "$MESSAGE_FILE"
    echo "Resource request sent to human inbox"
else
    # Other agent sending to code for fulfillment
    "$SCRIPT_DIR/bridge-send.sh" "$REQUESTING_AGENT" code "$PRIORITY" "Resource Request: $PURPOSE" "$MESSAGE_FILE"
    echo "Resource request sent to code agent"
fi

echo ""
echo "Request ID: $REQUEST_ID"
echo "Status: Pending $APPROVAL_STATUS"
echo ""

# Clean up temp file
rm -f "$MESSAGE_FILE"

exit 0
